# Generated by Django 3.0.6 on 2020-11-12 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vendors', '0007_auto_20201111_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
